<?php

namespace App\Constants;

class MoipConstants {

    const MOIP_TAX_DOCUMENT = "CPF";
    const MOIP_COUNTRY_CODE = 55;
    const MOIP_COUNTRY_NATIONALITY = "BR";
    const MOIP_COUNTRY_ABBR = "BRA";
    const MOIP_ACCOUNT_TYPE = "MERCHANT";
    const MOIP_SEGMENT = 16;

    const INTEGRACAO_WEBHOOK = 'WEBHOOK';
    const INTEGRACAO_CONTA_BANCARIA_CRIAR = 'CONTA_BANCARIA_CRIAR';
    const INTEGRACAO_CONTA_BANCARIA_EDITAR = 'CONTA_BANCARIA_EDITAR';
    const INTEGRACAO_CONTA_BANCARIA_EXCLUIR = 'CONTA_BANCARIA_EXCLUIR';
    const INTEGRACAO_CRIAR_CONTA_CHEF = 'CRIAR_CONTA_CHEF';
    const INTEGRACAO_CRIAR_PEDIDO = 'CRIAR_PEDIDO';
    const INTEGRACAO_REALIZAR_PAGAMENTO = 'REALIZAR_PAGAMENTO';
    const INTEGRACAO_SOLICITACAO_REEMBOLSO = 'REEMBOLSO';
    const INTEGRACAO_SOLICITACAO_SAQUE = 'SOLICITACAO_SAQUE';

}